### PR TITLE
Added the pushgateway health and ready endpoints

### PR DESCRIPTION
**Pull request by johnmehringer**
-- By adding these endpoints the prom-aggregation-gateway
   can be deployed using the prometheus-pushgateway helm chart
   with the following values settings.
```
image:
  repository: weaveworks/prom-aggregation-gateway
  tag: master-XXXXXXXX
  pullPolicy: IfNotPresent

extraArgs: ["-listen", ":9091"]
```
-- This is the code for the helm chart health checks
   which fail otherwise.
```
   livenessProbe:
     httpGet:
       path: /-/healthy
       port: 9091
     initialDelaySeconds: 10
     timeoutSeconds: 10
   readinessProbe:
     httpGet:
       path: /-/ready
       port: 9091
     initialDelaySeconds: 10
     timeoutSeconds: 10
```

This is the repo for the pushgateway helm chart.
  https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-pushgateway

### CODE REVIEW

**Comment by stabacco** [comment]
I'd be interested in this feature, since we're using helm to provision all of our stack. Any chance someone can have a look into it?

**Comment by bboreham** [comment]
Code looks ok; just have to figure out why CI has stopped working.

**Comment by bboreham** [comment]
Thanks!

**Comment by himeshkothari** [comment]
Hello, Can you please help to include the persistence flags from prometheus pushgateway chart to the aggregator gateway ?

## extraArgs:
##  - --persistence.file=/data/pushgateway.data
##  - --persistence.interval=5m

**Comment by bboreham** [comment]
This is an earlier contribution; not the place to ask for a feature. The “new issue” button is better. 

However nobody is very active in this project. You probably have to add the feature yourself or persuade someone else to add it.

**Comment by himeshkothari** [comment]
Thanks for the quick response Bryan.

Opened a new issue here : https://github.com/weaveworks/prom-aggregation-gateway/issues/63

Trying myself, struggling to understanding the code.

**Pull request merged**
