### PR TITLE
Add support PORT environment variable

### PR DESCRIPTION
**Pull request by identw**

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the PR!  Can you give some insight why this feature is needed, maybe by opening an issue?

**Comment by identw** [comment]
> Thanks for the PR! Can you give some insight why this feature is needed, maybe by opening an issue?

Hi! Thank you for answer.
I have a kubernetes cluster with a tuned pod security policy. Policies prohibit starting containers from root, and port 80 can only be listen from root. Therefore, I need the ability to change the port to > 1024

**Comment by bboreham** [comment]
OK, and does the existing `-listen` flag not work for you?

**Comment by identw** [comment]
> OK, and does the existing `-listen` flag not work for you?

Oh, sorry. Did not notice this parameter =(

**Comment by bboreham** [comment]
No problem!

PS you can bind to a <1024 port as a non-root user on Linux, if you have the `CAP_NET_BIND_SERVICE` [capability](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container).

**Comment by istvanjkb** [comment]
How can we use that flag? I don't find any documentation on it. I would like to use it on a kube cluster.

**Comment by bboreham** [comment]
Here it is in the source code: https://github.com/weaveworks/prom-aggregation-gateway/blob/123c6bfc5e07fb8f118c19b3281855bcb2463c39/cmd/prom-aggregation-gateway/main.go#L262

If you run with `-help` or something like that it will show all the options.

You can say `-listen=:9000` to listen on all addresses, port 9000, or add an address like `-listen=127.0.0.1:80`

**Pull request closed without merging**
